CREATE TABLE employee_ (
    emp_id INT  PRIMARY KEY,
    emp_name VARCHAR(100) NOT NULL,
    salary NUMERIC(10,2) NOT NULL,
    department VARCHAR(50)
);

-- 2. Insert sample data
INSERT INTO employee_ (emp_id,emp_name, salary, department) VALUES
(1,'Alice', 50000, 'HR'),
(2,'Bob', 60000, 'IT'),
(3,'Charlie', 55000, 'Finance');

CREATE OR REPLACE PROCEDURE UPDATA_SALARY_PROC(IN P_EMP_ID INT,INOUT P_SALARY NUMERIC(20,3),OUT
STATUS VARCHAR(20))
    AS
	$$
	DECLARE
	CURR_SAL NUMERIC(20,3);
	BEGIN

	SELECT SALARY+P_SALARY INTO CURR_SAL FROM EMPLOYEE_ WHERE EMP_ID=P_EMP_ID;
	IF NOT FOUND THEN
	RAISE EXCEPTION 'EMPLOYEE NOT FOUND';
	END IF;
	--CURR_SAL:=CURR_SALARY+P_SALARY;
	
	UPDATE EMPLOYEE_
	SET SALARY=CURR_SAL
	WHERE EMP_ID=P_EMP_ID;

	P_SALARY:=CURR_SAL;
	STATUS:='SUCCESS';

	EXCEPTION 
	WHEN OTHERS THEN
	IF SQLERRM LIKE '%EMPLOYEE NOT FOUND%' THEN 
	STATUS:='EMPLOYEE NOT FOUND';
	END IF;
	END
	$$ LANGUAGE PLPGSQL;

	
	DO
	$$
		DECLARE
		EMP_ID INT:=1;
		STATUS VARCHAR(20);
		SALARY NUMERIC(20,3):=500;
		BEGIN
		CALL UPDATA_SALARY_PROC(EMP_ID,SALARY,STATUS);
		RAISE NOTICE 'YOUR STATUS IS % ',STATUS;
		END;
	$$	
	
DO
	$$
		DECLARE
		EMP_ID INT:=99;
		STATUS VARCHAR(20);
		SALARY NUMERIC(20,3):=500;
		BEGIN
		CALL UPDATA_SALARY_PROC(EMP_ID,SALARY,STATUS);
		RAISE NOTICE 'YOUR STATUS IS % ',STATUS;
		END;
	$$	

SELECT * FROM EMPLOYEE_;	
